---
- name: 'i3 | Dependencies'
  ansible.builtin.apt:
    name:
      - feh
      - autoconf 
      - gcc 
      - make 
      - pkg-config 
      - libpam0g-dev 
      - libcairo2-dev 
      - libfontconfig1-dev 
      - libxcb-composite0-dev 
      - libev-dev 
      - libx11-xcb-dev 
      - libxcb-xkb-dev 
      - libxcb-xinerama0-dev 
      - libxcb-randr0-dev 
      - libxcb-image0-dev 
      - libxcb-util0-dev 
      - libxcb-xrm-dev 
      - libxkbcommon-dev 
      - libxkbcommon-x11-dev 
      - libjpeg-dev
    state: present
  become: true

- name: 'i3 | Install i3'
  ansible.builtin.apt:
    name:
      - i3
    state: present
  become: true

- name: 'i3 | Shell'
  shell: echo 'exec i3' > "{{ ansible_user_dir }}/.xinitrc"

- name: 'i3 | Configure i3'
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/roles/i3/files/i3"
    dest: "{{ ansible_user_dir }}/.config/"
    mode: 0644
    directory_mode: 0755
    force: true

- name: 'i3 | Remove Default i3lock'
  ansible.builtin.apt:
    name:
      -i3lock
    state: absent
  become: true

- name: 'i3 | i3 lock color'
  ansible.builtin.git:
    repo: https://github.com/Raymo111/i3lock-color
    dest: "{{ ansible_user_dir }}/.config/i3/i3lock-color"
