---
- name: "Brave | Install Dependencies"
  ansible.builtin.apt:
    name:
      - curl
    state: present
  become: true
  
- name: "Brave | Add Release Channel"
  shell: "sudo bash {{ playbook_dir }}/roles/brave/files/brave/brave.sh"
  become: true

- name: "Brave | Install Brave"
  ansible.builtin.apt:
    name: 
      - brave-browser
    state: present
  become: true
