---
- name: "Speedtest | Add speedtest repository"
  shell: "curl -s https://packagecloud.io/install/repositories/ookla/speedtest-cli/script.deb.sh | sudo bash"
  become: true

- name: "Speedtest | Install speedtest"
  ansible.builtin.apt:
    name:
      - speedtest
    state: present
  become: true
