---
- name: "Powershell | Install Dependencies"
  ansible.builtin.apt:
    name:
      - android-tools-adb
      - apt-transport-https
      - curl
      - gnupg2
    state: present
  become: true

- name: "Powershell | Add Repository and GPG Key"
  shell: "sudo bash {{ playbook_dir }}/roles/powershell/files/powershell/powershell.sh"
  become: true

- name: "Powershell | Install Powershell"
  ansible.builtin.apt:
    name:
      - powershell
    state: present
  become: true
