---
- name: "nvim | Install Dependencies"
  ansible.builtin.apt:
    name:
      - ninja-build
      - gettext
      - cmake
      - unzip
      - curl
    state: present
  become: true

- name: "nvim | Git Clone nvim"
  ansible.builtin.git:
    repo: https://github.com/neovim/neovim
    dest: "{{ ansible_user_dir }}/neovim"

- name: "nvim | Build nvim"
  shell: "cd {{ ansible_user_dir }}/neovim && make CMAKE_BUILD_TYPE=RelWithDebInfo"
  become: true

- name: "nvim | Install nvim"
  shell: "cd {{ ansible_user_dir }}/neovim && sudo make install"
  become: true

- name: "nvim | Configure nvim"
  ansible.builtin.copy:
  src: "{{ playbook_dir }}/roles/nvim/files/nvim"
  dest: "{{ ansible_user_dir }}/.config/"
  mode: 0755
  directory_mode: 0755
  force: true
